# Generated by Django 5.2 on 2025-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostorage', '0002_alter_group_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.CharField(),
        ),
    ]
