# Generated by Django 5.2 on 2025-05-10 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostorage', '0006_family_creator_alter_family_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'default_related_name': 'photos', 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='family',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='families',
            field=models.ManyToManyField(blank=True, to='photostorage.family', verbose_name='Семья'),
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(blank=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photostorage.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='families', through='photostorage.FamilyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
