# Generated by Django 5.2 on 2025-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostorage', '0007_alter_photo_options_rename_group_photo_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'default_related_name': 'photos', 'ordering': ('-created_date',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterField(
            model_name='family',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateField(verbose_name='Дата фотографии'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='families',
            field=models.ManyToManyField(to='photostorage.family', verbose_name='Семья'),
        ),
    ]
