# Generated by Django 5.2 on 2025-04-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
